name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  lint:
    name: "Check Code Linting"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: mv .env.ci .env
      - run: npm ci
      - run: npm run lint

  format:
    name: "Check Code Formatting"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: mv .env.ci .env
      - run: npm ci
      - run: npm run format:check

  typecheck:
    name: "Validate TypeScript Types"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: mv .env.ci .env
      - run: npm ci
      - run: npm run typecheck

  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [lint, format, typecheck]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: mv .env.ci .env
      - run: npm ci
      - run: npm run test

  build:
    name: "Build Project"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: test
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: mv .env.ci .env
      - run: npm ci
      - run: npm run build

  deploy:
    name: "Deploy to Vercel"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.18" # LTS
          cache: "npm"
      - run: npm install --global vercel@latest
      - run: echo running on branch ${BRANCH_NAME}

      - name: "Deploy to Vercel (Preview)"
        if: env.BRANCH_NAME != 'main'
        run: |
          vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }} > url.txt
          url=$(cat url.txt)
          echo "Deployment URL: '$url'"
          echo "PREVIEW_DEPLOYMENT_URL=$url" >> $GITHUB_ENV

      - name: "Post PR comment with deployment URL"
        if: github.event_name == 'pull_request'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "âœ… This PR was successfully deployed to a [preview Environment.](${{ env.PREVIEW_DEPLOYMENT_URL }})" --edit-last --create-if-none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Deploy to Vercel (Production)"
        if: env.BRANCH_NAME == 'main'
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
